- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
   - name: username
     prompt: enter username
     private: false

   - name: password
     prompt: enter password
     private: true

  tasks:
   - name: info
     ansible.builtin.debug:
      msg: " your username is {{ username }} and password is {{ password }}" 