- name: conditions in ansible
  hosts: local
  connection: local
  vars:
   Number_of_sessions: 7
  tasks:
   - name: check and print if no.of sessions are greater than 5
     ansible.builtin.debug:
      msg: "{{ yes,its greater than 5 }}"
     when: Number_of_sessions > 5
     