- name: command module and shell module
  hosts: local
  connection: local
  tasks:
  - name: test command module
    ansible.builtin.command: ls /home
    register: home_dirs
  - name: print output
    ansible.builtin.debug:
     msg: "{{ home_dirs }}"
  
  - name: test shell module
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: user_output

  - name: print output
    ansible.builtin.debug:
     msg: "{{ user_output }}"

  - name: test shell module
    ansible.builtin.shell: ls -ltr | files.txt
    register: files_output

  - name: print output
    ansible.builtin.debug:
     msg: "{{ files_output }}"


  


  

     
