- name: installing and removing packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name:  packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop: #list
    - { name: "mysql",state: "absent" }   #map/dictionary with key pair value
    - { name: "nginx",state: "present" }
    - { name: "zip",state: "present" }